import pandas as pd
import datetime

'''
 Clock in Clock Out is a class used to clock into and out of work, logging your hours into a csv file
 once the user chooses to export there time sheet it is exported as a pdf in Icodes timesheet format

'''
class CiCo:
    pass
    #constructor (DiscordUserID) -> void: uses the users discord ID to set the user account var for use later
    def __init__(self, DiscordUserID):
        self.UserAccount = self.get_account(DiscordUserID)

    #create account (DiscordUserID, FullName, Title) -> void: creates an account with CiCoAccount
    def create_account(DiscordUserID, FullName, Title):
        """
        creates a CiCoAccount standard account and saved it to CiCoUserData.csv

        Parameters:
             DiscordUserID (str | int): users discord id, pre generated by Discord
             FullName (str): Users full name, must align with what is on the generated timesheet by ICode
             Title (str) : Users job title, must align with what is on the generated timesheet by ICode

        :return: returns a string only if the user account is already saved to CiCoUserData.csv
        """
        UserData = pd.read_csv('CiCoUserData.csv', dtype={'col1':str, 'col2':str, 'col3':str})
        file_path = f"{DiscordUserID}.csv"
        DiscordUserID = str(DiscordUserID)
        if UserData.loc[UserData["UserID"] == DiscordUserID].empty:
            newRow = {"UserID": DiscordUserID,
                      "Name": FullName,
                      "Title": Title
                     }
            UserData.loc[len(UserData)] = newRow
            UserData.to_csv("CiCoUserData.csv", index=False)
        
        try:
            with open(file_path, 'x') as file:
                file.write("Date,Clock In,Clock Out,Total Hours\n")
        except FileExistsError:
            print(f"The file {file_path} already exists")

        else:
            return "account is already saved. use /view account to viw account details or /edit to edit any details about your account"




    # get account (DiscordUserID) -> dictionary: searches saved csv for account and creates a dictionary object
    def get_account(self, DiscordUserID):

        """
        Retrieves and returns a user's saved CiCo account.

        searches the 'CiCoUserData.csv' file for a row matching the
        provided DiscordUserID. If the account exists, it is converted into a
        dictionary containing the user's ID, name, and title. A status code of 0 is
        returned alongside the dictionary to indicate success.

        If the account is not found, the function returns an error message and a
        status code of 1

        Parameters:
            DiscordUserID (str | int): The Discord user ID used to locate the account.

        Returns:
            tuple:
                (dict, int) -> On success: a dictionary with account details and status code 0.
                (str, int)  -> On failure: an error message and status code 1.
        """
        UserData = pd.read_csv('CiCoUserData.csv', dtype={'UserID':str, 'Name':str, 'Title':str})
        DiscordUserID = str(DiscordUserID)
        UserAccount = UserData.loc[UserData["UserID"] == DiscordUserID]
        if not UserData.loc[UserData["UserID"] == DiscordUserID].empty:
            UserAccount = { "UserID":UserAccount["UserID"].values[0],
                            "Name": UserAccount["Name"].values[0],
                            "Title": UserAccount["Title"].values[0]
                          }
            return UserAccount, 0
        else:
            return "your account is not saved or im having issues accessing a file. use /create account to make an account", 1


    # TODO clock in (DiscordUserID) -> Void: uses the current data and time and writes it to the respective file for the user
    def clock_in(self, DiscordUserID):
        now = datetime.datetime.now()
        date = now.strftime("%m/%d/%Y")
        time = now.strftime("%H:%M")
        time_sheet_file = f"{DiscordUserID}.csv"
        time_sheet = pd.read_csv(time_sheet_file, dtype={'Date':str, 'Clock In':str, 'Clock Out':str, 'Total Hours':str})
        newRow = { "Date": date,
                    "Clock In": time,
                    "Clock Out": "",
                    "Total Hours": ""
                 }
        time_sheet.loc[len(time_sheet)] = newRow
        time_sheet.to_csv(time_sheet_file, index=False)

    # TODO clock out (DiscordUserID) -> String: uses the current data and time and writes it the respective file for the user then returns the time in hours exe: 1 hour 30 minutes 1.30
    def clock_out(self, DiscordUserID):
        now = datetime.datetime.now()
        date = now.strftime("%m/%d/%Y")
        time = now.strftime("%H:%M")
        time_sheet_file = f"{DiscordUserID}.csv"
        time_sheet = pd.read_csv(time_sheet_file, dtype={'Date':str, 'Clock In':str, 'Clock Out':str, 'Total Hours':str})
        #find the last clock in entry without a clock out
        last_clock_in_index = time_sheet[(time_sheet["Clock Out"] == "") & (time_sheet["Date"] == date)].index
        if not last_clock_in_index.empty:
            idx = last_clock_in_index[-1]
            clock_in_time_str = time_sheet.at[idx, "Clock In"]
            clock_in_time = datetime.datetime.strptime(f"{date} {clock_in_time_str}", "%m/%d/%Y %H:%M")
            clock_out_time = now
            total_hours = clock_out_time - clock_in_time
            print(total_hours)
            total_hours_str = f"{total_hours}"
            time_sheet.at[idx, "Clock Out"] = time
            time_sheet.at[idx, "Total Hours"] = total_hours_str
            time_sheet.to_csv(time_sheet_file, index=False)
            return total_hours_str
        pass

    # TODO export (DiscordUserID) -> PDF File: writes the saved user data to a pdf in Icodes timesheet format


    #edit (FullName=None, Title=None) -> Void:
    def edit_account(self, FullName=None, Title=None):

        """
        Updates the current user's account information.

        Uses the data stored in self.UserAccount to locate the user's row in
        'CiCoUserData.csv'. If found, updates the Name and/or Title fields with any
        provided values, writes the changes back to the CSV, and updates the local
        account cache.

        Parameters:
            FullName (str, optional): New full name to save.
            Title (str, optional): New job title to save.

        Returns:
            str: Success message, or an error message if the account cannot be found.
        """

        # self.UserAccount = (dict, status_code)
        account_data, status_code = self.UserAccount

        if status_code != 0:
            return "No account found. Please create an account first."

        # Load CSV
        UserData = pd.read_csv('CiCoUserData.csv', dtype={'UserID': str, 'Name': str, 'Title': str})

        # Locate the index of the user's row
        user_index = UserData.index[UserData["UserID"] == account_data["UserID"]].tolist()
        if not user_index:
            return "Error: User account not found in file."

        idx = user_index[0]

        # Update fields if new values are provided
        if FullName is not None:
            UserData.at[idx, "Name"] = FullName
            account_data["Name"] = FullName
        if Title is not None:
            UserData.at[idx, "Title"] = Title
            account_data["Title"] = Title

        # Save updated data back to CSV
        UserData.to_csv("CiCoUserData.csv", index=False)

        # Update self.UserAccount with the new data
        self.UserAccount = (account_data, 0)

        return f"Account for {account_data['UserID']} updated successfully."



